# Generated by Django 5.0.6 on 2025-10-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='doc_number',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_file',
            field=models.FileField(default=1, upload_to='documents/verification/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('driver_license', 'Driver License'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
