# Generated by Django 5.0.6 on 2025-10-11 02:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='ID of the user performing the activity')),
                ('activity_type', models.CharField(help_text="e.g., 'post_view', 'like', 'purchase'", max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Additional data')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
